apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction
  namespace: ipl-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
        - name: prediction
          image: fawazcp/ipl-prediction:v1   # change to your repo
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prediction
  namespace: ipl-prediction
spec:
  selector:
    app: prediction
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

